// Generated by gencpp from file shooter/Sensors.msg
// DO NOT EDIT!


#ifndef SHOOTER_MESSAGE_SENSORS_H
#define SHOOTER_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shooter
{
template <class ContainerAllocator>
struct Sensors_
{
  typedef Sensors_<ContainerAllocator> Type;

  Sensors_()
    : hall_effect(false)
    , encoder(0.0)  {
    }
  Sensors_(const ContainerAllocator& _alloc)
    : hall_effect(false)
    , encoder(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _hall_effect_type;
  _hall_effect_type hall_effect;

   typedef float _encoder_type;
  _encoder_type encoder;




  typedef boost::shared_ptr< ::shooter::Sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shooter::Sensors_<ContainerAllocator> const> ConstPtr;

}; // struct Sensors_

typedef ::shooter::Sensors_<std::allocator<void> > Sensors;

typedef boost::shared_ptr< ::shooter::Sensors > SensorsPtr;
typedef boost::shared_ptr< ::shooter::Sensors const> SensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shooter::Sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shooter::Sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shooter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shooter': ['/home/ubuntu/shooter_ws/src/shooter/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shooter::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shooter::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shooter::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shooter::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shooter::Sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shooter::Sensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shooter::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7cfdfbbaadd9e2973865db3746b46cc";
  }

  static const char* value(const ::shooter::Sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7cfdfbbaadd9e29ULL;
  static const uint64_t static_value2 = 0x73865db3746b46ccULL;
};

template<class ContainerAllocator>
struct DataType< ::shooter::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shooter/Sensors";
  }

  static const char* value(const ::shooter::Sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shooter::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool hall_effect\n\
float32 encoder\n\
";
  }

  static const char* value(const ::shooter::Sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shooter::Sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hall_effect);
      stream.next(m.encoder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shooter::Sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shooter::Sensors_<ContainerAllocator>& v)
  {
    s << indent << "hall_effect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hall_effect);
    s << indent << "encoder: ";
    Printer<float>::stream(s, indent + "  ", v.encoder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHOOTER_MESSAGE_SENSORS_H
